### PR TITLE
🇪🇸(ES) Guide

### PR DESCRIPTION
**Pull request by khalidbelk**
✅ Done : 

+ New pages:
    - Writing code: data, registers, multitude
    - Instructions: mov, math, jumps, functions, conditionals, loops, stack
+ Minor fixes

### CODE REVIEW

**Comment by khalidbelk** [comment]
Hey @bellesea :) could you check this out plz ?

**Comment by khalidbelk** [comment]
@bellesea

**Comment by bellesea** [comment]
hiii @khalidbelk sorry for the delay! this is so awesome, thank you :))))

**Comment by khalidbelk** [comment]
> hiii @khalidbelk sorry for the delay! this is so awesome, thank you :)))) you're so cool!

Your welcome !! Thank you Belle !

**Pull request merged**
