### PR TITLE
Intel-8085 Folder created

### PR DESCRIPTION
**Pull request by amandewatnitrr**
Added detailed info about Intel 8085 in the readme and soon will be adding the code and rest of architecture explanation and basic commands. #67

### CODE REVIEW

**Comment by bellesea** [comment]
Hii @amandewatnitrr thank you so much for this PR! Apologies for the delayed review, was not sure if it was ready to merge. This looks awesome, will you be adding a code example? Also, as this is adding new content, please give us a few days to fact-check it before merging. Thank you so so much!

**Comment by bellesea** [comment]
Hey @amandewatnitrr thanks for putting this together! This content looks really good! Could you please share your sources just so we can double check on licenses and ensure we can add this content to the guide?

Thank you so much and really appreciate it!

**Comment by amandewatnitrr** [comment]
Hello @bellesea,
The Source links have been attached below:
1. https://www.tutorialspoint.com/microprocessor/microprocessor_8085_architecture.htm
2. https://www.geeksforgeeks.org/architecture-of-8085-microprocessor/

**Comment by bellesea** [comment]
Hello @amandewatnitrr! Thank you so much for sharing these resources, making the pull request, and patience with allowing us to review it. We really appreciate your help in making assembly easier to learn for everyone! That said, due to copyright issues, this PR is not yet ready to be merged :(

We recognise that you put a lot of work into your PR, and it's not a direct copy. We understand and really appreciate your effort! That said, it's too similar to not be considered infringement.

If you're willing, you can still make this PR! However, you would need to rewrite some of the information with original wording and explanation. If you use material from other sources, please ensure the license is compatible (we can work with you to check). For example, Geeks for Geeks has a license that allows sharing and adaptation with attribution. I've attached the license at the end of this comment. 

I completely understand if you're not interested in updating this PR but if you are, and make the adjustments, we'd love to review this again! I'm so sorry we can't merge this yet. Still, thank you very much for the help, and have a great day!

**License info:**
https://www.tutorialspoint.com/microprocessor/microprocessor_8085_architecture.htm#
does not have an open source licence (https://www.tutorialspoint.com/about/about_terms_of_use.htm):

> The web pages, tutorials, code snippets, graphics, diagrams, artwork and study material (referred to as "contents") are the copyrighted property of Tutorials Point India Limited unless you have uploaded/hosted it yourself. It is strictly prohibited to retain, reuse, reproduce or publish the contents or a portion of contents in any format, without our written consent.

https://www.geeksforgeeks.org/architecture-of-8085-microprocessor/
has some sort of license but would require attribution: https://www.geeksforgeeks.org/copyright-information/

> You are free to:
> Share — copy and redistribute the material in any medium or format
> Adapt — remix, transform, and build upon the material for any purpose.
> Under the following terms:
> Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
> Hyperlink each article directly back to their user profile page on the source site (e.g., for the article https://www.geeksforgeeks.org/rc4-encryption-algorithm/ the link to the author profile would be https://auth.geeksforgeeks.org/user/Sally%20Jarkas/articles)
> If you are copying more than 50% of your Contents from our site you necessarily need to add up the following tag in the head section of the website, For example:
> https://example.com/abc.html copies the content from
> https://www.geeksforgeeks.org/xyz then
> https://example.com/abc.html should contain < link rel="canonical" href= ["https://www.geeksforgeeks.org/xyz/"](https://www.geeksforgeeks.org/xyz/) /> in the < head> tag.
> Share Alike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.
> No additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.

**Comment by amandewatnitrr** [comment]
@bellesea would be glad to work on the copyright issue, just suggest me any website where i can plag check the content.

**Pull request closed without merging**
